#ifndef ENUMMENSAJES_H_INCLUDED
#define ENUMMENSAJES_H_INCLUDED
#include <stdio.h>

typedef enum {OK, YA_EXISTE_CAMIONERO, NO_EXISTE_CAMIONERO, YA_EXISTE_CAMION, NO_EXISTE_CAMION, ITER_CAMIONEROS_VACIO, DICC_CAMIONEROS_VACIO,DICC_CAMIONES_VACIO} TipoMensaje;

void MostrarMensaje(TipoMensaje tipo);

#endif // ENUMMENSAJES_H_INCLUDED